FROM node:22.3.0
WORKDIR /web

ARG SERVICE_PORT
ARG SERVICE_PORT_SSL
ENV NODE_ENV=production

COPY . .
RUN npm install --verbose && npm run build

EXPOSE ${SERVICE_PORT} ${SERVICE_PORT_SSL}
CMD npm run start