apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  # namespace: monitoring
stringData:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring-tea.svc:9090",
                "version": 1
            }
        ]
    }
type: Opaque
