
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-auth
  labels:
    app: teastore
    run: teastore-auth
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30085   # expose to the outside
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
  selector:
    run: teastore-auth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
  labels:
    app: teastore
    run: teastore-auth
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
    spec:
      containers:
        - name: teastore-auth
          image: macsalvation/teastore-auth:v0.2.0
          # image: johnzr/cnae-g8-teastore-auth-origin:v1.0
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9464
              name: metrics
          env:
            - name: HOST_NAME
              value: "teastore-auth"
            - name: REGISTRY_HOST
              value: "teastore-registry"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

---