---

apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
  selector:
    run: teastore-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
        - name: teastore-db
          image: macsalvation/teastore-db:v0.2.0-dbmid
          imagePullPolicy: "Always"
          # image: johnzr/cnae-g8-teastore-db-origin:v1.0
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9464
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi


