
---

apiVersion: v1
kind: Service
metadata:
  name: teastore-image
  labels:
    app: teastore
    run: teastore-image
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30084   # expose to the outside
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
  selector:
    run: teastore-image

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
  labels:
    app: teastore
    run: teastore-image
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      containers:
        - name: teastore-image
          image: macsalvation/teastore-image:v0.2.0-dbmid
          imagePullPolicy: "Always"
          # image: johnzr/cnae-g8-teastore-image-origin:v1.0
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9464
              name: metrics
          env:
            - name: HOST_NAME
              value: "teastore-image"
            - name: REGISTRY_HOST
              value: "teastore-registry"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
---