
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-persistence
  labels:
    app: teastore
    run: teastore-persistence
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30083   # expose to the outside
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
  selector:
    run: teastore-persistence

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
  labels:
    app: teastore
    run: teastore-persistence
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      containers:
        - name: teastore-persistence
          image: macsalvation/teastore-persistence:v0.1.0
          imagePullPolicy: "Always"
          # image: johnzr/cnae-g8-teastore-persistence-origin:v1.0
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9464
              name: metrics
          env:
            - name: HOST_NAME
              value: "teastore-persistence"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: DB_HOST
              value: "teastore-db"
            - name: DB_PORT
              value: "3306"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
---