
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-persistence
  labels:
    app: teastore-persistence
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30083   # expose to the outside
      protocol: TCP
  selector:
    app: teastore-persistence

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
  labels:
    app: teastore-persistence
spec:
  selector:
    matchLabels:
      app: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore-persistence
    spec:
      containers:
        - name: teastore-persistence
          image: macsalvation/teastore-persistence:v0.2.0
          imagePullPolicy: "Always"
          # image: johnzr/cnae-g8-teastore-persistence-origin:v1.0
          ports:
            - containerPort: 8080
              name: http
            # - containerPort: 9464
            #   name: metrics
          envFrom:
            - configMapRef:
                name: teastore-share-config
            - configMapRef:
                name: teastore-persistence-config
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
---