
---

apiVersion: v1
kind: Service
metadata:
  name: teastore-recommender
  labels:
    app: teastore-recommender
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30082   # expose to the outside
      protocol: TCP
    # - name: metrics
    #   port: 9464
    #   targetPort: 9464
    #   protocol: TCP
  selector:
    app: teastore-recommender

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-recommender
  labels:
    app: teastore-recommender
spec:
  selector:
    matchLabels:
      app: teastore-recommender
  template:
    metadata:
      labels:
        app: teastore-recommender
    spec:
      containers:
        - name: teastore-recommender
          image: macsalvation/teastore-recommender:v0.2.0
          imagePullPolicy: "Always"
          # image: johnzr/cnae-g8-teastore-recommender-origin:v1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: teastore-webui-config
            - configMapRef:
                name: teastore-recommender-config
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
---