---

apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    run: teastore-webui
  ports:
    - name: http
      port: 8080
      nodePort: 30080   # expose to the outside
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
  

---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: teastore-webui-ingress
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: web # only http for now
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: teastore-webui
#             port:
#               number: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-webui
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-webui
    spec:
      containers:
        - name: teastore-webui
          image: macsalvation/teastore-webui:v0.1.0
          imagePullPolicy: "Always"
          # image: johnzr/cnae-g8-teastore-webui-origin:v1.0
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9464
              name: metrics
          env:
            - name: HOST_NAME
              value: "teastore-webui"
            - name: REGISTRY_HOST
              value: "teastore-registry"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi

---