FROM icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi

# Set environment variables for custom ports
ENV WARM_ENDPOINT=false
ENV WARM_OPENAPI_ENDPOINT=false
ENV OPENJ9_SCC=false

COPY --chown=1001:0 /src/main/liberty/config /config

RUN features.sh

COPY --chown=1001:0 target/*.war /config/apps

RUN configure.sh
