FROM icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi

ENV SERVICE_PORT=8080
ENV WARM_ENDPOINT=false
ENV WARM_OPENAPI_ENDPOINT=false

COPY --chown=1001:0 /src/main/liberty/config /config

RUN features.sh

COPY --chown=1001:0 target/*.war /config/apps

RUN configure.sh
