FROM nginx:1.27.0-alpine

ARG DB_SIZE

RUN mkdir -p /data/images/tools.descartes.teastore.image
COPY nginx.conf /etc/nginx/conf.d/default.template
COPY generated_images/db-${DB_SIZE} /data/images/tools.descartes.teastore.image

CMD sh -c "envsubst \"`env | awk -F = '{printf \" \\\\$%s\", $1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"